### ISSUE TITLE
Refactor data structure for raw results

### ISSUE THREAD

**Issue by Ethan-Russell** [e4st-dev/E4ST.jl#182]
Right now, the raw results contain a single number for every constraint, variable, and expression, either the value or the shadow price.  Sometimes, it is necessary to have multiple pieces of information for these.  For example the reduced cost of a variable bound.  It would be great for raw results to be a nested dictionary like:
```yml
variable_name:
  value:
  reduced_cost:
variable2_name:
  value:
constraint1_name:
  shadow_price:
```
