### ISSUE TITLE
Add Objective Discounting

### ISSUE THREAD

**Issue by Ethan-Russell** [e4st-dev/E4ST.jl#58]
@sallyrobson from our conversation today, we want an annual objective expression, so that we can sum with a (custom) discounting function.

I'm imagining providing something like the in the config file:
```yaml
discounting:
  type:  Weighted
  rate:  0.03
```
